# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: moenet.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmoenet.proto\x12\x0cmoenet.proto\"+\n\tTimestamp\x12\x0f\n\x07seconds\x18\x01 \x01(\x03\x12\r\n\x05nanos\x18\x02 \x01(\x05\"0\n\rTranslation3d\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\"\xcb\x01\n\x0fObjectDetection\x12*\n\ttimestamp\x18\x01 \x01(\x0b\x32\x17.moenet.proto.Timestamp\x12\x10\n\x08label_id\x18\x02 \x01(\x05\x12\x12\n\nconfidence\x18\x03 \x01(\x01\x12\x32\n\rpositionRobot\x18\x04 \x01(\x0b\x32\x1b.moenet.proto.Translation3d\x12\x32\n\rpositionField\x18\x05 \x01(\x0b\x32\x1b.moenet.proto.Translation3d\"U\n\x10ObjectDetections\x12\x0e\n\x06labels\x18\x01 \x03(\t\x12\x31\n\ndetections\x18\x02 \x03(\x0b\x32\x1d.moenet.proto.ObjectDetectionB\x1c\n\x18\x63om.mindlin.moenet.protoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'moenet_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\030com.mindlin.moenet.protoP\001'
  _globals['_TIMESTAMP']._serialized_start=30
  _globals['_TIMESTAMP']._serialized_end=73
  _globals['_TRANSLATION3D']._serialized_start=75
  _globals['_TRANSLATION3D']._serialized_end=123
  _globals['_OBJECTDETECTION']._serialized_start=126
  _globals['_OBJECTDETECTION']._serialized_end=329
  _globals['_OBJECTDETECTIONS']._serialized_start=331
  _globals['_OBJECTDETECTIONS']._serialized_end=416
# @@protoc_insertion_point(module_scope)
